### ISSUE TITLE
feature request: api to update the task details

### ISSUE THREAD

**Issue by hrj** [ctongfei/progressbar#1]
Hi,

Thanks for creating this library. We are trying to use this in [this project](https://github.com/UprootLabs/grinder).

Would be nice if there was a way to set some text in the progress bar that indicates what the current task is doing. Something like:

```scala
pb.setTaskDescription("absolute-position")
```

which would render the progress bar as, for example:
```
Test 62% [================         ] 621/1000 (0:00:12 / 0:00:07) "absolute-position"
```

**Comment by ctongfei** [comment]
It is set via the first argument of the constructor. val pb = new ProgressBar("your task description", maxvalue).

**Comment by hrj** [comment]
yeah, but that is static. I would like to have a dynamic component, which describes the currently executing task.

**Comment by ctongfei** [comment]
I understand your requirements but after a little thought I found out that it is hard to implement under the current model. It currently does not use any Cursor library and it only depends on the \r control character to move the cursor to the beginning of a line (moving the cursor to the beginning does not erase the line). By adding the end-of-line description will make the length of each output non-uniform: 
```
Test 62% [================         ] 621/1000 (0:00:12 / 0:00:07) "absolute-position"
```
Later if we change the description to "abs":
```
Test 82% [==================    ] 821/1000 (0:00:18 / 0:00:05) "abs".......................
```
the "..............." part will still be the original text "olute-position" that will not be erased.

To implement your suggestion I have to switch to a model that depends on a cursor library. I may do that in the future but that's probably not something I'll do in this month.

**Comment by hrj** [comment]
A quick attempt at a simplistic solution:

You could keep track of the number of characters emitted in the previous print. When you print a new progress bar, you can erase (with spaces) any left over characters.

In pseudo code,
```
var prevCount = 0
val thisCount = thisLine.lenght
print thisLine
if (thisCount < prevCount) {
  print spaces * (thisCount - prevCount)
}
prevCount = thisCount
```

**Comment by ctongfei** [comment]
You can use `"me.tongfei" % "progressbar_2.11" % "0.3.2-SNAPSHOT"` on the Sonatype **snapshots** server now.

**Comment by hrj** [comment]
Works great. Thanks!
