### ISSUE TITLE
Extra message wraps to next line, causes artefacts

### ISSUE THREAD

**Issue by mattcg** [ctongfei/progressbar#10]
Thank you for this great, simple library. There's just one tiny bug that I can see. When the extra message doesn't fit in the remaining columns after the progress bar, it wraps to the next line.

This means that when the progress bar is next rendered, it leaves an artefact of the previous render on the line above.

This could be fixed by trimming the extra message so that it fits. Adjusting progress bar width on initialisation isn't an option because we're dealing with unpredictable lengths here (path names, in this case).

**Comment by ctongfei** [comment]
Thanks for pointing out this! Trimming the extra message seems to be a good idea. I'll fix this in the next version.

**Comment by ctongfei** [comment]
Fixed in 0.5.2.

**Comment by PabloLeon** [comment]
It would be great to have a way to allow longer than default extra messages (i.e. pass an argument for max width/characters at which to trim the message).
