### ISSUE TITLE
Parallel progress bars are overwriting each other

### ISSUE THREAD

**Issue by kilianfriedrich** [ctongfei/progressbar#103]
Hi, I was trying to use two parallel Progressbars at the same time but they'll "overwrite" each other (meaning that both bars are in the same line so that only one bar is shown).

I'm using IntelliJ's included Terminal.

Am I doing something wrong or is the parallel feature just buggy? My code is like this:
```
    public void savePdfs(String bookId) {
       // ...
        for (Scale scale : scales) {
            new Thread(() -> writePdf(scale)).start();
        }
    }

    private void writePdf(Scale scale) {
        for (PageWsto pageWsto : ProgressBar.wrap(scale.getPages(), "Scale #" + scale.getIndex())) {
            // ...
        }
    }
```

The result looks like the following:
![grafik](https://user-images.githubusercontent.com/38128547/121429551-53d9b580-c977-11eb-8fe1-1185961a3ddb.png)
Progressbar "Scale #1" is missing. However when both Threads are finished, the last Console state is correct:
![grafik](https://user-images.githubusercontent.com/38128547/121429397-2856cb00-c977-11eb-8e36-e2a952b3bd27.png)

What am I doing wrong there?

**Comment by ctongfei** [comment]
IntelliJ's included terminal does not support the cursor-moving ANSI control characters. It simply does not work.
Any normal terminal (linux/mac; or WSL under Windows) should work.

**Comment by ctongfei** [comment]
For future reference: This bug depends on the solution of this issue: https://youtrack.jetbrains.com/issue/IDEA-149959
