### ISSUE TITLE
0.9.2 does not work well on Windows DOS or Cygwin ...

### ISSUE THREAD

**Issue by aguedeney** [ctongfei/progressbar#109]
First, progressbars and mulitbars works very well on Linux terminals in general.

I realize a Windows OS is challenging.  I also realize you don't have access to a Windows OS.  However, I wanted to make sure folks know not to expect this to work on Windows terminals.
 
The simple test uses multi-bars.

It does this using Cygwin:
```
Test2   1% [=>                                                                                                                 ]   2/200 (0:00:00 / 0:00:08)
Test1   1% [=>                                                                                                                 ]   1/100 (0:00:01 / 0:01:45)
Test2   1% [=>                                                                                                                 ]   3/200 (0:00:01 / 0:01:17) ←
Test2   2% [==>                                                                                                                ]   4/200 (0:00:02 / 0:01:41) ←
```
It does this using cmd.exe (DOS box):
```
>java -jar vfy-snippet.jar
Test2   6% [==>                                  ]  13/200 (0:00:12 / 0:02:52)

**Comment by Avec112** [comment]
I get the same with both cmd and Powershell on Win 7. 
Progress is printed vertically for every horisontal step. 

I want to start my application with a bat-file, but Progressbar does act as expected compared to when I run the application inside my IDE.

**Comment by ctongfei** [comment]
See #100 : `Progressbar` is known to be broken on Cygwin / cmd / Powershell when using multiple bars. Multiple bars are only working under Linux/Mac/WSL.

**Comment by aguedeney** [comment]
This is now working fine in version 0.9.4 on Windows DOS Prompt and Cygwin. I'm on the latest version of Windows 10 Pro and Cygwin to date.

**Comment by aguedeney** [comment]
This is now working fine in version 0.9.4 on Windows DOS Prompt and Cygwin. I'm on the latest version of Windows 10 Pro and Cygwin to date.
