### ISSUE TITLE
Ability to rewind/reset progress

### ISSUE THREAD

**Issue by TIBCOeddie** [ctongfei/progressbar#113]
If I am looping, I might want to show progress, and upon completing (or at any point, really) I would like to continue using the same bar, but re-set to zero. There appears to be no API that accomplishes this.

**Comment by ctongfei** [comment]
This is not recommended since it meddles with how the progress bar estimates the time of completion (a recommended way is to start a new progress bar). But if you must, you can do
```java
bar.stepTo(0)
```
to forcibly set the progress to 0.

**Comment by TIBCOeddie** [comment]
As you point out, stepTo(0) doesn't really reset things, thus hold this
issue for the improvement. I would have a reset() that would be equivalent
to creating a new one, but without a newline/new visual progress bar.
