### ISSUE TITLE
Wrap outputstream as well

### ISSUE THREAD

**Issue by azachar** [ctongfei/progressbar#114]
Hi there!
A very nice tool!

Could you please add also support for output streams?

 For instance the library I am using for datalake is providing only output stream, so what I did is this:

```java
ProgressBar pb = new ProgressBarBuilder()
			    .setTaskName("Downloading "+pathItem.getName())
			    .setUnit("MiB", 1024*1024)
			    .build();
		
		pb.maxHint(pathItem.getContentLength());

OutputStream targetStream = new FileOutputStream(outputFile) {
			@Override
			public void write(byte[] b) throws IOException {
				super.write(b);
				pb.stepBy(b.length);
			}
			
			@Override
			public void write(int b) throws IOException {
				super.write(b);
				pb.step();
			}
			
			@Override
			public void write(byte[] b, int off, int len) throws IOException {
				super.write(b, off, len);
				pb.stepBy(b.length);
			}
		};
```

I guess that anonym class should be part of this project somehow. 

Cheers,
Andrej

**Comment by ctongfei** [comment]
Thanks Andrej for the suggestion! I guess we should do `OutputStream` and `Writer` then?

**Comment by azachar** [comment]
Sure, that would be cool! 

Ps: also adding a method for a complete done would be great! 

Cheers,

Andrej

**Comment by ctongfei** [comment]
@azachar what do you mean by a complete done?
