### ISSUE TITLE
Display progress bar immediately

### ISSUE THREAD

**Issue by azachar** [ctongfei/progressbar#117]
Hello, 

Would it be possible to display an initial progress bar immediately or after calling let say "show" method.

My issue is that first calling on stepBy(xx) is done after couple of minutes, due to nature of the operation that I am unable to track. 
For the final user it looks that application is not doing anything. What I would like to achieve is to display a progress bar with zero progress plus with unknown estimate.

Does this make sense to you?

Thank you!

Cheers,
Andrej

**Comment by ctongfei** [comment]
Thanks Andrej. This will be a bugfix in the next version.
