### ISSUE TITLE
No showing properly

### ISSUE THREAD

**Issue by danyaljj** [ctongfei/progressbar#12]
This is what I see in mac. Where do I go wrong? 

<img width="1253" alt="screen shot 2017-01-10 at 12 45 24 am" src="https://cloud.githubusercontent.com/assets/2441454/21796399/2756c408-d6ce-11e6-9e0e-64add3c7611f.png">

**Comment by ctongfei** [comment]
What is the [error] prefix at the beginning of the line?
Are you using a logger like slf4j?

**Comment by danyaljj** [comment]
hmmm ... I thought it's related to `prgressbar` .... 
yeah I used sl4j.

**Comment by ctongfei** [comment]
`ProgressBar` is not printing the "error" prefix at the beginning of the status line.
I wonder if that is something that `slf4j` used. It somehow redirected the `System.out` stream to decorate it with the `error` prefix. Just my speculations

**Comment by ctongfei** [comment]
Fixed by #54 in version `0.8.0`.
