### ISSUE TITLE
setMaxRenderedLength behaves starangly

### ISSUE THREAD

**Issue by MagnusErikssonAB** [ctongfei/progressbar#129]
How exactly is the setMaxRenderedLength method intended to work? What is the unit specified?

I have tried various values and with 75 it is just a few characters wide, with 200 it fills half the screen?!?

The length of the bar also seems to change depending on the length of the task name specified (seem like the longer the task name the shorter the bas becomes)....

**Comment by ctongfei** [comment]
The length does not refer to the number of the bar characters: it refers to the whole output sequence including the task name, estimated time left, etc.

**Comment by MagnusErikssonAB** [comment]
So the intended "scale" of this is "terminaL characters" (setMaxRenderedLength(80) would be for a typical 80 character wide terminal window).... Would be a great addition to the documentation as this is as far as I have seen not mentioned.
