### ISSUE TITLE
Can one disable the "time estimate"?

### ISSUE THREAD

**Issue by MagnusErikssonAB** [ctongfei/progressbar#131]
For my tests (that do not progress very linearly) the "estimated remaining time" (I assume it is - the second time display after the "/") is very inaccurate and I would prefer to disable it - is this possible? If not it would be a nice feature.

**Comment by ctongfei** [comment]
Right now it cannot be disabled. There are two ways: (1) enable a way to disable the estimated remaining time; (2) use a fancier method to estimate instead of just doing linear extrapolation as it is right now. Which one do you prefer?

**Comment by MagnusErikssonAB** [comment]
Short term disabling would fit my needs. Long term one could even consider
ability for the user of the library to add a function for calculation that
fits the use-case.

Best Regards
Magnus

**Comment by ctongfei** [comment]
Will be fixed in `0.9.4`, and added a new configurable setting in `ProgressBarBuilder`: you can now use `setETAFunction(BiFunction<ProgressState, Duration, Optional<Duration>>)` to provide with your own estimator of remaining time (for non-linear progresses).
