### ISSUE TITLE
Feature Request: Append to line & Wipe bar

### ISSUE THREAD

**Issue by mattparkins** [ctongfei/progressbar#135]
I'd love 

1. the ability to append the progress bar to the line it is on?  (Could pass the column number if required)

2. the ability to make the progress bar disappear when .close() is called.

Are these possible?

**Comment by ctongfei** [comment]
Hello @mattparkins,
For (1), there is `.setExtraMessage()` which might suit your need.
For (2), I'll add this to the next version -- thanks for the suggestion!

**Comment by mattparkins** [comment]
Ah thanks, brilliant!

**Comment by ctongfei** [comment]
In the next version in the `ProgressBarBuilder` you can now call `.clearDisplayOnFinish()` to configure such requested behavior.
