### ISSUE TITLE
progress bar looks strange

### ISSUE THREAD

**Issue by earlyou** [ctongfei/progressbar#138]
![progress bar error](https://user-images.githubusercontent.com/103157377/179190130-473fb1b5-c435-45fc-8113-f8731ad428cb.gif)

HI,
I'm currently using Eclipse and the bar looks strange.
I wonder if there is no `\r`method. And the bar constantly changes its shape.

here is my example codes
``` java
try (ProgressBar pb1 = new ProgressBar("Interting", totalCount)) {
     if (condition) {
          for (int i = 0; i < numofrows; i++) {
               pb1.step();
               // ...
          }
     }else{
          for (int i = 0; i < totalpage-1; i++) {
               for (int j = 0; j < numofrows; j++) {
                    pb1.step();
                    // ...
               }
          }
     }
     pb1.close();
}
```

``` java
ProgressBar pb1 = new ProgressBar("Inserting", totalCount);
if (condition) {
     for (int i = 0; i < numofrows; i++) {
          pb1.step();
          // ...
     }
}else{
     for (int i = 0; i < totalpage-1; i++) {
          for (int j = 0; j < numofrows; j++) {
               pb1.step();
               // ...
          }
     }
}
pb1.close();
```
am i using it right?
both results are the same

+++++
![progress bar linux](https://user-images.githubusercontent.com/103157377/179196814-27dc5cd9-8a11-4ba1-aa32-1725bd6c4ee4.gif)
I uploaded my project to Linux CentOs 7 Server and the progress bar works just fine

Is it only me bar working weird on Eclipse?

**Comment by ctongfei** [comment]
Your terminal in Eclipse does not seem to support ANSI support symbols. You can use `ProgressBarStyle.ASCII` to remove some of these weird fonts. This is a problem of Eclipse.

As for your Linux Server, the block can be removed by changing your terminal font (Courier New does not have full support for these symbols).

**Comment by earlyou** [comment]
Thanks for your reply. By the way your project is awesome :)
