### ISSUE TITLE
long vars to track current/max in ProgressState class

### ISSUE THREAD

**Issue by vitobellini** [ctongfei/progressbar#14]
Hi,
I've found your class really useful! I'm just disappointed in the use of int instead of long.
We use progress bar when we have several items to process, so an integer value cannot represent such hunge range of values.
I'm processing an huge dataset with billions of items, I cannot use your implementation with int :(

Can you please consider to replace integer with long in ProgressState's class attributes current and max? 

```
class ProgressState {
    String task;
    int current = 0;
    int max = 0;
    LocalDateTime startTime = null;
    String extraMessage = "";
...
}
```

**Comment by ctongfei** [comment]
Fixed in v0.5.3. (it may take a few hours for mvn to complete the synchronization of the jars). Thanks!
