### ISSUE TITLE
Work around bugs in java.util.Spliterator#estimateSize

### ISSUE THREAD

**Issue by seanf** [ctongfei/progressbar#141]
Some `Spliterator`s have bugs in their `estimateSize` methods, and introducing ProgressBar can trigger these bugs when it tries to determine the initialMax value. It would be good to have `ProgressBar.wrap` catch any exceptions and do its best to continue. This of courses raises the question of exception logging.

Would you be open to a PR which makes this change?

**Comment by ctongfei** [comment]
It sounds interesting -- how should we handle the exception? Just ignore it and continue as if it is indefinite?

**Comment by seanf** [comment]
Thank you!
