### ISSUE TITLE
ProgressBarBuilder()#setEtaFunction is pointless because all methods in ProgressState are package-private

### ISSUE THREAD

**Issue by natanfudge** [ctongfei/progressbar#147]
`setEtaFunction` accepts a `(BiFunction<ProgressState, Duration, Optional<Duration>>`, but it's impossible to use `ProgressState` for consumers because everything there is package-private. `setEtaFunction` should either accept a Bifunction that provides objects that are actually usable, or `ProgressState` and its methods should become public.

**Comment by ctongfei** [comment]
Thanks @natanfudge ! My fault, will have to make that class public.

**Comment by ctongfei** [comment]
See #146: I think a better way is to change `setETAFunction` so that it accepts `BiFunction<ProgressBar, Duration, Optional<Duration>>`. Let me know if you have any objections.

**Comment by ctongfei** [comment]
Fixed in `0.9.5`.
