### ISSUE TITLE
progressbar cannot be used as a module

### ISSUE THREAD

**Issue by clo-vis** [ctongfei/progressbar#149]
By adding
`Automatic-Module-Name: me.tongfei.progressbar`
to MANIFEST.MF, progressbar could directly be used also as an automatic module (like [jline](https://repo1.maven.org/maven2/org/jline/jline/3.21.0/jline-3.21.0.pom))

**Comment by ctongfei** [comment]
Thanks! This will be in the next release.

**Comment by ctongfei** [comment]
Fixed in release `0.10.0`.
