### ISSUE TITLE
Ctrl - c to stop java console program slowly

### ISSUE THREAD

**Issue by quantrpeter** [ctongfei/progressbar#150]
Ctrl - c to stop java console program slowly. It takes around 10 seconds to stop

**Comment by ctongfei** [comment]
Have you tried `Ctrl` + `\`, that sends `SIGQUIT`?

**Comment by ctongfei** [comment]
This is the expected Java behavior for threads I believe. If you want to have the process shut down when being signalled `SIGINT`, maybe add a shutdown hook? See https://stackoverflow.com/questions/1611931/catching-ctrlc-in-java
