### ISSUE TITLE
Allow users to setup their own style

### ISSUE THREAD

**Issue by PakhomovAlexander** [ctongfei/progressbar#151]
Hi, I wonder to propose an improvement for the Progress bar API. This would be nice if users could provide their own characters for the progress bar style and color.  For example, I want a green unicode bar in my application but now it is impossible to configure.

Would you like to discuss the API changes and accept the PR? Thanks.

**Comment by ctongfei** [comment]
Hi Alexander! A PR is definitely welcome for this -- I guess what you want to do is to modify `ProgressBarStyle` to an inheritable class rather than an `enum`.

**Comment by PakhomovAlexander** [comment]
Perfect! Yes, I would like to create an API that will allow users to extend the `ProgressBarStyle` through a builder-like style.

**Comment by PakhomovAlexander** [comment]
Hi @ctongfei , here is my PR #152

**Comment by ctongfei** [comment]
Thanks for the PR! Merged in release `0.10.0`.
