### ISSUE TITLE
Real module-info.java

### ISSUE THREAD

**Issue by bowbahdoe** [ctongfei/progressbar#154]
Currently, progressbar can't be used with `jlink`.

It should be [pretty easy](https://github.com/moditect/moditect#adding-a-module-descriptor-to-the-project-jar) nowadays to add a module-info without sacrificing java 8 compatibility, so adding a module-info in a multi-release jar would be appropriate.

**Comment by ctongfei** [comment]
Supersedes #149, #153.

**Comment by ctongfei** [comment]
Fixed in release `0.10.0`.
