### ISSUE TITLE
Ability to pause and resume the progressbar

### ISSUE THREAD

**Issue by hrj** [ctongfei/progressbar#17]
In our test harness, we allow execution of the tests to be paused and then, continued at a later time.

It would be great if the progress bar can be paused and resumed (I think it used to work fine before the multi-threaded version).

**Comment by ctongfei** [comment]
Pause/resume was never implemented in the single-threaded version: the estimated time remaining needs to be recomputed while taking into account of the timespan paused.

**Comment by ctongfei** [comment]
Fixed in `0.9.0`: There are `pause` and `resume` methods in `ProgressBar`s.
