### ISSUE TITLE
support for org.slf4j.Logger

### ISSUE THREAD

**Issue by MasseGuillaume** [ctongfei/progressbar#18]
It's pretty hard to adapt an java.in.OutputStream to the Logger. It would be nice to provide an interface to print lines.

**Comment by ctongfei** [comment]
This is, I think, the same problem as #12 ?

**Comment by HSAR** [comment]
Extra mention for this one! The package really well, would be nice to be use it in projects that have a "more complete" logging system.

**Comment by RAYs3T** [comment]
Same with log4j2

My output looks like this:
![image](https://user-images.githubusercontent.com/16596807/53685555-96ce6c80-3d1c-11e9-829b-a73da311e0f3.png)

Support for loggers would be awesome!

**Comment by RAYs3T** [comment]
@ctongfei Do you see any possible work-a-round to get it working (clean) together with log4j?
I would love to use it in my program, but at the same time i need my console logging to be readable.
(See the screenshot from my post above)

**Comment by ctongfei** [comment]
Fixed by #54 in version `0.8.0`.
