### ISSUE TITLE
Fix java compiler version in  maven build

### ISSUE THREAD

**Issue by ccamel** [ctongfei/progressbar#19]
According to the documentation of maven, for the [maven compiler plugin](https://maven.apache.org/plugins/maven-compiler-plugin/) the default source and target settings are 1.5, independently of the JDK that maven runs with. 

However, the `progressbar` project use some java 8 specifics, like the [LocalDateTime](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html) class ([see code](https://github.com/ctongfei/progressbar/blob/master/src/main/java/me/tongfei/progressbar/ProgressState.java#L19)) which appeared since 1.8.

This means that when invoking maven, it will produce the appropriate byte code, but when using, it throws errors when running on any JVM prior to 8.

I guess it would be nice to have the classes generated with the correct target version of the JVM.

**Comment by ctongfei** [comment]
Fixed in `pom.xml`. Thanks!
