### ISSUE TITLE
[feature request] for updating the task with fixed values

### ISSUE THREAD

**Issue by svenmauer** [ctongfei/progressbar#2]
Hello,

thank you for creating this wonderful library. I need for an upload app the feature that I can use as alternative to "pb.stepBy(n); " an alternative method to give a fixed value. As example when I call the method with 100 then should the showed value be "100/maxvalue" and not 100 + previous step.

I hope you can implement this.

Greetings
Sven

-- [EDIT] --
As a workaround I have delete the + sign in the "pb.stepBy(n)" method.

**Comment by ctongfei** [comment]
I'll add a `stepTo` method. Thanks!

**Comment by ramalhoruben** [comment]
I solved it like this:

public class ProgressBar extends me.tongfei.progressbar.ProgressBar{

    private double df, diff;
    private long lp;
    private int step;

    public ProgressBar(String task, long max) {
        super(task, 100);
        df = max/100.0;
    }

    public void setProgress(long p) {
        diff = (p-lp)/df + diff - step;
        step = (int) Math.floor(diff);

        this.stepBy(step);
        lp = p;
    }
}

**Comment by ctongfei** [comment]
Deployed version 0.4.1. 
Should be synced to the mvn central soon.

Thanks!
