### ISSUE TITLE
Problem in IntelliJ

### ISSUE THREAD

**Issue by felixdivo** [ctongfei/progressbar#21]
When running in the [IntelliJ IDE](https://www.jetbrains.com/idea/) integrated console no correct progress bar is drawn. The same code works fine on the default Windows command line. 

![image](https://user-images.githubusercontent.com/4403130/30513770-5ba08136-9b09-11e7-9e41-818fc3195474.png)

**Comment by AbhinavVishak** [comment]
This I believe is an issue due to intellij doing clipping in the console. 

see https://stackoverflow.com/questions/24936479/why-there-are-only-75-visible-characters-in-intellij-ideas-embedded-terminal
and 
https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-117552

**Comment by felixdivo** [comment]
Oh wow, how ugly. But well, not your fault. ;)
