### ISSUE TITLE
Support DUMB terminals

### ISSUE THREAD

**Issue by koppor** [ctongfei/progressbar#24]
When using the library on CircleCI, I get following output:

![grafik](https://user-images.githubusercontent.com/1366654/36358225-0aa7a67a-150b-11e8-86c5-d0f5ff3360ff.png)

Would it be possible to just go to a new line (instead of the beginning of the same line) in case of a DUMB terminal?

See also: https://stackoverflow.com/q/39001517/873282

**Comment by ctongfei** [comment]
Without the ability to move cursors, you cannot print a sensible progress bar (what you'll get is a sequence of bars: I don't think that'll look good) -- so I would suggest not using a progress bar if the terminal is limited?

**Comment by koppor** [comment]
For me, a sequence of bars would be OK. What also would work is an output like:

```
Check 45% 45/100
Check 46% 46/100
...
```

**Comment by ctongfei** [comment]
You can easily do that yourself if that is what you like. I don't know how can I check the capabilities of the terminal that the program is currently running in, so this would be `wontfix`.

**Comment by koppor** [comment]
I want to use the lib as is in different settings... Not adding some ifs
around...

Maybe, System.getEnv("TERM") is the way to go within the code? 😇

**Comment by ctongfei** [comment]
Ah I understand. You can open a PR for this functionality -- Sorry for being very busy and not able to update this library soon.

**Comment by ctongfei** [comment]
This is a bit complicated -- it probably interferes with how it works in IntelliJ IDEA.
What is your `System.getenv("TERM")` output on your dumb terminal?

**Comment by koppor** [comment]
I use CircleCI and there it is set to `dumb`: https://circleci.com/gh/ryanwohara/test-2.0/79#config/containers/0 (source: https://discuss.circleci.com/t/circleci-terminal-is-a-tty-but-term-is-not-set/9965/4)

**Comment by glasser** [comment]
As a super basic hack, you can do this (note: this is Kotlin not Java):

```
			builder.setPrintStream(object : PrintStream(System.err) {
				// By code inspection, ProgressThread calls this function with '\r' to clear the line.
				// We change it to start a new line instead. (This does mean that, if reading via a line-based
				// mechanism like `kubectl logs -f`, we won't see lines until the next line starts, but still
				// better than not seeing them until program end.)
				override fun print(c: Char) {
					super.print(if (c == '\r') '\n' else c)
				}
			})
```

**Comment by ctongfei** [comment]
This is now customizable using the customized `ProgressBarConsumer` as is introduced in `0.8.0`.
