### ISSUE TITLE
Control-C not working in Windows

### ISSUE THREAD

**Issue by albancolley** [ctongfei/progressbar#25]
Aborting the code with Control-C  is not working in windows.  This seem to be an issue with getting the terminal column width in jline2.12.  This code sets a system hook that consumes the Control-C. 

Updating to pom to jline 2.14.3 (or greater) resolves this issue.

**Comment by ctongfei** [comment]
Thanks for pointing this out. Updating JLine was on the radar.

**Comment by ctongfei** [comment]
Should be fixed in 0.6.0 since JLine has been updated to 3.x.
