### ISSUE TITLE
Ctor with initialMax, updateIntervalMillis and stye.

### ISSUE THREAD

**Issue by khmarbaise** [ctongfei/progressbar#26]
You can initialise the progressbar in different way but unfortunately there is one option missing from point of view:
```java
ProgressBar(String task, long initialMax, int updateIntervalMillis, ProgressBarStyle style)
```

**Comment by ctongfei** [comment]
The constructor has too much parameters now. I'm considering switching to the Builder pattern.

**Comment by ctongfei** [comment]
#36 `0.7.0` published using builder patterns. No need for these constructors now!
