### ISSUE TITLE
Simple API for range

### ISSUE THREAD

**Issue by michaelmior** [ctongfei/progressbar#44]
Unless I'm missing something, if I just want a progress bar for something that goes over a range of input, I have to use the imperative syntax which implies two additional levels of nesting. It would be great if there were a simple declarative API that accepts two integers and lets me iterate over the range between them.

I tried using an `IntStream` with the existing declarative API which almost works, but doesn't maintain the total size.

**Comment by ctongfei** [comment]
Can you use Guava / ApacheCommonsLang's `Range` class for this?

**Comment by michaelmior** [comment]
Perhaps, but it would be unfortunate to have to pull in either of those for a fairly simple problem.

**Comment by ctongfei** [comment]
The principled way is that you continue using `IntStream` and I'll add a proper `ProgressBar.wrap(Stream)` function that reads the estimated remaining size as the max limit of the progress bar.  Thanks for pointing this out -- this function will be added in the next release.

**Comment by michaelmior** [comment]
That would be great :) That was actually how I expected things to work already. Thanks!

**Comment by ctongfei** [comment]
I encountered problems with parallel streams. This may not be ready in a few days since I'm busy with other stuffs.

**Comment by ctongfei** [comment]
Now supported in `0.7.2`.

**Comment by michaelmior** [comment]
Awesome! Thank you :)
