### ISSUE TITLE
Progressbar seems to hang for the duration of one update if the computation is very short.

### ISSUE THREAD

**Issue by denisrosset** [ctongfei/progressbar#50]
I'm using this wonderful library from Scala; it seems that the minimal delay incurred is the one given in `updateIntervalMillis`.

Is there an obvious way to see why? (Busy on squashing bugs right now, but I can work on a minimal reproducing example on request).

This is on `0.7.3`.

**Comment by ctongfei** [comment]
I don't understand -- the progressbar flushes itself (redraw on the terminal) every `updateIntervalMillis` milliseconds. Are you saying that your progress finishes before 1 `updateIntervalMillis` and the program still runs for 1 `updateIntervalMillis` until it terminates?
