### ISSUE TITLE
off by one?

### ISSUE THREAD

**Issue by rualpe** [ctongfei/progressbar#6]
(love this new unicode progress bar, thanks!)

I feel there might be off-by one error here:
`Retrying those that failed 100% │███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ │ 8974535/8974535 (0:06:33 / 0:00:00) 
`

**Comment by ctongfei** [comment]
Try using the "="-symbol based v0.4.2 for now.
I'll look into this. Thanks!

**Comment by ctongfei** [comment]
Fixed. Use 0.5.0.

**Comment by rualpe** [comment]
cool. thanks! works for me.
