### ISSUE TITLE
Off by one when wrapping InputStream

### ISSUE THREAD

**Issue by mordechaim** [ctongfei/progressbar#60]
![image](https://user-images.githubusercontent.com/12547785/73202591-584a5900-4109-11ea-81b6-d407c7247636.png)

I use `ProgressBar.wrap(InputStream, ProgressBarBuilder)` where the stream is created by `URL.openStream()`. I set the initial max to the actual file size. Reducing the max by one (or even 10) has zero effect and will still show the actual file size (as if I set it to the correct size).

**Comment by ctongfei** [comment]
Just to confirm -- you mean that you want to override the default size (as computed by the underlying stream) to a customized size using `ProgressBarBuilder`? 

Why do you want to do this? I assume that the underlying actual file size is the size of the progress bar you want?

**Comment by mordechaim** [comment]
> you want to override the default size (as computed by the underlying stream)

Wrapping the stream without setting the max initial ended up showing question marks (unknown file size) and a messed up progress bar:
![image](https://user-images.githubusercontent.com/12547785/73212587-8be2ae80-411c-11ea-8a56-e4157ae64588.png)


 So I set the max initial to the file size (correctly shown at the right side of the `/`) but the total bytes downloaded (at the left of `/`) is off by one even though the actual file is downloaded in full and my OS shows the file size correctly.

**Comment by mordechaim** [comment]
Just checked, when using the `ProgressBar.wrap(InputStream, String)` constructor, it will show question marks, but using `ProgressBar.wrap(InputStream, ProgressBarBuilder)` *even if I don't set the max initial* it will show exactly like the first snip, i.e. correct file size but still off by one in progress.

**Comment by mordechaim** [comment]
Looking at the code, `Util.getInputStreamSize()` returns -1 for non-file streams (which I use) and that is used in the string constructor, but passing my own builder and leaving out the max initial it somehow detects it correctly.

**Comment by mordechaim** [comment]
OK! I got it. When reading the stream, I read until OEF by:

```java
while ((read = in.read(buffer, 0, buffer.length)) > -1) {
    // do something.
}
```

This causes [stepBy](https://github.com/ctongfei/progressbar/blob/master/src/main/java/me/tongfei/progressbar/wrapped/ProgressBarWrappedInputStream.java#L45) to step back by one on EOF.

**Comment by ctongfei** [comment]
So it is still a bug, right? 
In https://github.com/ctongfei/progressbar/blob/master/src/main/java/me/tongfei/progressbar/wrapped/ProgressBarWrappedInputStream.java#L45, if `stream.read() == -1`, the progress bar should not `stepBy` -1.

**Comment by ctongfei** [comment]
> Looking at the code, `Util.getInputStreamSize()` returns -1 for non-file streams (which I use) and that is used in the string constructor, but passing my own builder and leaving out the max initial it somehow detects it correctly.

This surprises me -- if it is not a `FileInputStream` the max initial should not be detected?

**Comment by mordechaim** [comment]
> So it is still a bug, right?

Yes, this is a bug. [here](https://github.com/ctongfei/progressbar/blob/master/src/main/java/me/tongfei/progressbar/wrapped/ProgressBarWrappedInputStream.java#L31) you do it correctly.

**Comment by mordechaim** [comment]
Ok, so downloading with a small delay reveals why this is happening. Not that it detects the file size, it just downloaded so fast that I couldn't see it.

[This](https://github.com/ctongfei/progressbar/blob/master/src/main/java/me/tongfei/progressbar/wrapped/ProgressBarWrappedInputStream.java#L31) line of code shows us that the max increases as the download proceeds but of-course won't backtrack when the stepBy is -1, so it ended up showing the correct file size on the right size of the slash. The progress bar itself always showed 100% (only jumping back to 99% on EOF.

Additionally, it was not detected as indefinite when building my own as [this](https://github.com/ctongfei/progressbar/blob/master/src/main/java/me/tongfei/progressbar/ProgressState.java#L22) only checks for -1, not 0. So [this](https://github.com/ctongfei/progressbar/blob/master/src/main/java/me/tongfei/progressbar/DefaultProgressBarRenderer.java#L95) was never executed.

**Comment by ctongfei** [comment]
Thanks @mordechaim ! These will be fixed in the next release.

**Comment by mordechaim** [comment]
I think I know your whole codebase by now 😉, it took me some half-hour or so.

**Comment by ctongfei** [comment]
A pull request would be welcome!

**Comment by mordechaim** [comment]
Do you want to handle 0 max as indefinite?

**Comment by mordechaim** [comment]
> Do you want to handle 0 max as indefinite?

Or perhaps use -1 as the default value of the initial max in the builder.

**Comment by ctongfei** [comment]
-1 should be the default max of the initial max. 0 means an empty sequence.
