### ISSUE TITLE
Custom width

### ISSUE THREAD

**Issue by koppor** [ctongfei/progressbar#71]
I would like to set a custom width for the progressbar

When running the progressbar, I see following:

![grafik](https://user-images.githubusercontent.com/1366654/79393288-514b1e00-7f75-11ea-9b6b-da959ec7315b.png)

In ConEmu (cmd.exe)

![grafik](https://user-images.githubusercontent.com/1366654/79393408-90796f00-7f75-11ea-8e85-58c9174edbf1.png)

I would like to manually set the width using the [Builder](https://tongfei.me/progressbar/builder/). However, I did not see an option `setWidth()`.

Maybe refs https://github.com/ctongfei/progressbar/issues/23 and https://github.com/ctongfei/progressbar/issues/32.

**Comment by koppor** [comment]
Also helpful for usage at nohup:

![grafik](https://user-images.githubusercontent.com/1366654/79509565-0ba55880-803c-11ea-8524-8fd825b51de9.png)

**Comment by ctongfei** [comment]
The master head now has `setMaxWidth` in the builder.
