### ISSUE TITLE
Enable null ProgressBar

### ISSUE THREAD

**Issue by koppor** [ctongfei/progressbar#74]
When "code and fix"ing and application, I tend to use "[Logger.debug](https://tinylog.org/v2/logging/#plain-text)", which doesn't appear at the console. - I would like to keep the ProgressBar-code, but just "disable" it. Think, the easiest way is to provide a "NullProgressBar", which hast the same interface as the normal ProgressBar, but outputs to "/dev/null" (i.e., does nothing).

**Comment by ctongfei** [comment]
Well in this case you could use `new DelegateProgressBarConsumer(logger::debug)`?

**Comment by koppor** [comment]
Thank you for the hint, I implemented it like that - and it works! 🎉 

```java
    try (ProgressBar progressBar = new ProgressBarBuilder()
      .setTaskName("Collect all files")
      .setInitialMax(100L)
      .setConsumer(new DelegatingProgressBarConsumer(x -> {}))
      .build();
    ) {
```

Maybe worth to add it into the documentation?
