### ISSUE TITLE
Window 10 cmd.exe progressbar default width is too small.

### ISSUE THREAD

**Issue by aguedeney** [ctongfei/progressbar#78]
This might be a custom setting as indicated in issue #71.  However, the default with in the cmd.exe context regardless of mode lines and cols setting are unaffected.  This might be due to the underlining jline terminal but I couldn't find a definitive way to change it. I'm sure others may (or will) have this problem.

**Comment by ctongfei** [comment]
Thanks @aguedeney -- the next version will add a `setWidth` method.

**Comment by aguedeney** [comment]
Thank you! Looking forward to it.

**Comment by ctongfei** [comment]
Fixed in `0.9.0`.
