### ISSUE TITLE
IntelliJ IDEA not showing speed or count progress, but only without using SLF4j

### ISSUE THREAD

**Issue by astubbs** [ctongfei/progressbar#79]
Might be related to #23 and #21, whenever I use the bar from within IDEA (works as expected outside), I only see the bar, I never see the speed or progress counter, I only see them once the progress is complete.

Eg running RangeTest, during run I see:
![Screen Shot 2020-06-26 at 12 34 59 PM](https://user-images.githubusercontent.com/3414/85852973-9d9eaf80-b7a9-11ea-85a6-726adcf9c313.png)

Upon completion I see:
![Screen Shot 2020-06-26 at 12 35 10 PM](https://user-images.githubusercontent.com/3414/85853004-a4c5bd80-b7a9-11ea-939c-a99cf773b477.png)

The SLF4J test I get as expected:
![Screen Shot 2020-06-26 at 12 35 57 PM](https://user-images.githubusercontent.com/3414/85853008-a7281780-b7a9-11ea-969f-376d9a910781.png)

Haven't attempted to fix, but let me know if I can help in any way. Love the library! If I get some time this weekend I might take a crack.

```
IntelliJ IDEA 2020.1.1 (Community Edition)
Build #IC-201.7223.91, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: analyze.exceptions.on.the.fly=true, debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: awesome.console, claims.bold.intellij.avro, Lombook Plugin, com.thoughtworks.gauge, org.avaje.ebean11.enhancer, org.intellij.scala, org.jetbrains.kotlin, mobi.hsz.idea.gitignore, MavenRunHelper, BashSupport, aws.toolkit, org.asciidoctor.intellij.asciidoc
```

**Comment by astubbs** [comment]
It's quite odd, you can see the render is correct, it's somewhere between the print stream#print and what shows up on the console:
![Screen Shot 2020-06-26 at 12 44 08 PM](https://user-images.githubusercontent.com/3414/85853750-00447b00-b7ab-11ea-89b3-42610bedba3b.png)
<img width="1076" alt="Screen Shot 2020-06-26 at 12 44 03 PM" src="https://user-images.githubusercontent.com/3414/85853751-00dd1180-b7ab-11ea-963b-953a6c1c8538.png">

**Comment by ctongfei** [comment]
Thanks @astubbs ! 
Oh yeah, I have encountered this myself. This is because IntelliJ's test environment did not flush the output frequently.
If you just use IntelliJ's internal Run/Debug, it works perfectly.
This is probably out of my hand to fix.
