### ISSUE TITLE
Ability to extend DefaultProgressBarRenderer

### ISSUE THREAD

**Issue by ksvladimir** [ctongfei/progressbar#81]
My use-case requires a different way to compute speed/eta (using point-in-time speed vs. average). I could accomplish this fairly easily by extending DefaultProgressBarRenderer... except I can't because it's constructor and most methods are private. Could you please make the constructor and methods public or at least protected? The same applies to other classes, like ConsoleProgressBarConsumer.

**Comment by ksvladimir** [comment]
I'd be happy to submit a PR if that would help!

**Comment by ctongfei** [comment]
Fixed in `0.9.0`.
