### ISSUE TITLE
Many classes are protected and can't be extended

### ISSUE THREAD

**Issue by mprevost-gradkell** [ctongfei/progressbar#86]
Awesome progress bar.  I love it.  Trying to make something like DelegatingProgressBarConsumer so that I can get the rendered string on the console but also to use in an output file.  Not sure why the  ConsoleProgressBarConsumer constructor would be protected.  Also the me.tongfei.progressbar.Util class with the Terminal stuff is also protected.

Perhaps I should be going about this in a different way, but it would be nice to be able to extend these classes.  Thanks for the awesome work!

**Comment by ctongfei** [comment]
The `DelegatingProgressBarConsumer` is basically a wrapper around a lambda function that consumes the rendered progress bar output. I suppose that you can plug in any behavior you want into the `Consumer<String>` argument of the constructor of the `DelegatingProgressBarConsumer`? Or are there additional functionalities that you would like?

**Comment by mprevost-gradkell** [comment]
Was looking to make a ProgressBarConsumer that may or may not write to the
console.  So I wanted to be able to at least instantiate a Console
ProgressBarConsumer so that I can optionally delegate to it.  I do have
something working that is working sort of the way I want with
DelegatingProgressBarConsumer.   But it would be nice to be able to
instantiate and/or extend ConsoleProgressBarConsumer.

'Preciate the fine project!


*Mike R. Prevost*
*DBsign Data Security Suite*
*Gradkell Systems, Inc.*
Phone: *256-701-4664*
US Central Time, GMT-6

**Comment by ctongfei** [comment]
Fixed in `0.9.0`.
