### ISSUE TITLE
last refresh

### ISSUE THREAD

**Issue by rualpe** [ctongfei/progressbar#9]
hmm, regretfully, something is not right with last refresh.

I see it finishes on random number again:
Retrying those that failed   0% │                                                                                                                                        │    4876/8974535 (0:00:01 / 0:31:36) 
Retrying those that failed   0% │                                                                                                                                        │    4342/8974535 (0:00:01 / 0:35:34) 

(while I set 10000 items to work upon).

Remember I've suggested one more refresh after 'while(running)' in ProgressThread.run in my pull req?

**Comment by ctongfei** [comment]
Got it, I changed the while loop to a do-while loop but it doesn't seem to solve the issue. I'll fix this later.

**Comment by rualpe** [comment]
There is one more thing about that: stop does just kill and exists.
I would very much prefer that upon exit from stop() we had nice last refresh done.
So subsequent prints that my script does would not interlace with late exit from ProgressThread while loop...

**Comment by ctongfei** [comment]
Try refresh your maven cache and download 0.5.1 again and see if it is fixed. I don't to want to increment the version number too frequently.

**Comment by rualpe** [comment]
"one more thing" was not handled.

Simple test:
Add this like after stop in test:
```
        System.out.println("hello?");
```

One would expect progress bar to stop and then print that "hello", right?

Here's what we have now:
```
Test 100% │████████████████████████████████│ 12977/12977 (0:00:36 / 0:00:00) hello?
Test 100% │████████████████████████████████│ 12999/12999 (0:00:36 / 0:00:00) 
```

which is sad.
it happens clearly because of no synchronisation between stop and actual stopping.
hence main thread continues after stop() and lets "hello" appear before actual stopping.

additional little sad moment is that wait for updateInterval.


maybe you'd consider adding some synchronisation here? and some small wakeup so not to wait for that sleep to finish itself?

**Comment by ctongfei** [comment]
Starting from v0.4.2 progressbar's default output stream is System.err instead of System.out.
It is probably a synchronization error between System.out and System.err. I cannot find the problem now (I've tried flushing both streams but no use)

**Comment by ctongfei** [comment]
These are two different streams so the synchronization is hard. See https://stackoverflow.com/questions/1883321/java-system-out-println-and-system-err-println-out-of-order/1883333#1883333. Where do you get that result? IntelliJ/Eclipse or command line?

**Comment by rualpe** [comment]
Both.
I feel this might be trivial:
1. main thread calls stop
2. main thread sets flag that ProgressThread should exit
3. main thread exists from stop
4. main thread prints stuff on output
5. ProgressThread sleeps
6. ProgressThread goes out of sleep and discovers it should exit the loop
7. ProgressThread exists loop and does last refresh.

One way is just to put a long sleep to stop() to ensure ProgressThread would go out of it's sleep.
Better way is to wake up ProgressThread from sleep, wait for it to die, and only then exit stop()

**Comment by ctongfei** [comment]
I tried `thread.join()` in the main thread and it does not solve this issue. The problem arises because there is no synchronization mechanism between the `System.out` stream and `System.err` stream when they are being output on the terminal.

**Comment by rualpe** [comment]
thread.join() works find for me, both in IntelliJ window and on console.

**Comment by ctongfei** [comment]
thread.join() works for me in the Console but does not work for me in IntelliJ. I'm going to update it to `thread.join()`. The IntelliJ/Eclipse problem will not be fixed.

**Comment by rualpe** [comment]
maybe somebody else might come up with some ideas.
good for me!
