### ISSUE TITLE
[extra] show progress only when step is called

### ISSUE THREAD

**Issue by elanzini** [ctongfei/progressbar#91]
when there is a lot of logging already coming from the process we are tracking progress of, we might want to silence the progressbar and only print the progress when any `step` function is called. This makes the logging more organized, without having the progressbar printed every couple of lines.

**Comment by ctongfei** [comment]
Thanks @elanzini ! I think this would also improve the performance of progressbars as it reduces the number of calls to print.

**Comment by ctongfei** [comment]
Released in version `0.9.1`.
