### ISSUE TITLE
Documentation for imperative usage is not up to date

### ISSUE THREAD

**Issue by Cyb0rk** [ctongfei/progressbar#92]
Hello,

the documentation at http://tongfei.me/progressbar/imperative-usage/ says:

`// Use ProgressBar("Test", 100, ProgressBarStyle.ASCII) if you want ASCII output style`

But there is no constructor for this:

![image](https://user-images.githubusercontent.com/95137/102407191-fe39d700-3feb-11eb-967a-9ffb68677fe1.png)

It would be great to easily change the Style via this. Could you add it?

Best regards

**Comment by ctongfei** [comment]
Hi @Cyb0rk ! This is a deprecated old constructor (I'll keep note to update the documentation).
We have switched to the more principled builder-pattern approach. You can set the style using `ProgressBarBuilder` as described in http://tongfei.me/progressbar/builder/.

**Comment by Cyb0rk** [comment]
Hello @ctongfei 

Thanks for your information. If I use the ProgessBarBuilder, is there any way to access the ProgressBar itself?
Because I need to use the .step() function because I access the ProgessBar from another thread.

For example:

```java
try (ProgressBar progressBar = new ProgressBar("Reading", fileCollection.size(), 100, System.err, ProgressBarStyle.ASCII, " Files", 1, false, null, ChronoUnit.SECONDS, 0L, Duration.ZERO)) {
	ExecutorService executorService = Executors.newFixedThreadPool(8);

	for (File file : fileCollection) {
		executorService.submit(new Thread(new ReadingThread(file, fileMap, progressBar)));
	}

	executorService.shutdown();
	try {
		boolean finished = executorService.awaitTermination(30, TimeUnit.MINUTES);
	} catch (InterruptedException e) {
		e.printStackTrace();
	}
}
```

Then I update the progress from the ReadingThread Class.

**Comment by ctongfei** [comment]
`ProgressBarBuilder().setXXX().setXXX().build()` returns the `ProgressBar` object.

**Comment by Cyb0rk** [comment]
@ctongfei Thanks, works. But interesting behaviour: The progressbar seems to behave differently.

When I use the code from above, I'll get the normal progress bar:

`Reading 100% [============================] 150/150 Files (0:00:00 / 0:00:00)`

But when I use 

```java
ProgressBarBuilder progressBarBuilder = new ProgressBarBuilder()
		.setStyle(ProgressBarStyle.ASCII)
		.setTaskName("Reading")
		.setUnit(" Files", 1)
		.setUpdateIntervalMillis(100);
ProgressBar progressBar = progressBarBuilder.build();

ExecutorService executorService = Executors.newFixedThreadPool(threads);

for (File file : ProgressBar.wrap(fileCollection, progressBarBuilder)) {
	executorService.submit(new Thread(new ReadingThread(file, fileMap, progressBar)));
}

executorService.shutdown();
try {
	boolean finished = executorService.awaitTermination(1, TimeUnit.HOURS);
} catch (InterruptedException e) {
	e.printStackTrace();
}
```

The Bar get interrupted (finished?) and starts a new one which isn't finished:

```
Reading 100% [============================] 150/150 Files (0:00:00 / 0:00:00)
Reading ? % [     =                              ] 149/? Files (0:00:00 / ?)
```

When I add `.setInitialMax(fileCollection.size())` it the second bar has a max limit, but this is still one bar too much:

```
Hashing 100% [============================] 150/150 Files (0:00:00 / 0:00:00)
Hashing  99% [===========================>] 149/150 Files (0:00:00 / 0:00:00)
```

I can't figure out why this happens. Maybe because of my progressBarBuilder and a progressBar variable?

By the way: In my Thread, I only use `progressBar.step()`; after finishing each thread.

**Comment by ctongfei** [comment]
```java
for (File file : ProgressBar.wrap(fileCollection, progressBarBuilder)) {
```
This line generates a new `ProgressBar` instance that is attached to the `fileCollection`, which is different from what you get from `.build()`.

To remedy this, try the following using the imperative mode:
```java
ProgressBarBuilder progressBarBuilder = new ProgressBarBuilder()
		.setStyle(ProgressBarStyle.ASCII)
		.setTaskName("Reading")
		.setUnit(" Files", 1)
		.setUpdateIntervalMillis(100);

try (ProgressBar progressBar = progressBarBuilder.build()) {  // build the progress bar instance here
  for (File file : fileCollection) {
	executorService.submit(new Thread(new ReadingThread(file, fileMap, progressBar)));
        progressBar.step();
  }
}
```

**Comment by ctongfei** [comment]
Usually when you want the `ProgressBar` instance itself, use the imperative mode rather than the declarative `ProgressBar.wrap` mode.

**Comment by Cyb0rk** [comment]
Thanks a lot and for updating the documentation!
