### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by rayastar** [ctongfei/progressbar#99]
![image](https://user-images.githubusercontent.com/7265549/115778710-c12d8900-a3bf-11eb-810f-5adab92dcb6b.png)

Hey, build jar file and catch this error. Winfows 10

**Comment by ctongfei** [comment]
`close` is here: https://github.com/ctongfei/progressbar/blob/main/src/main/java/me/tongfei/progressbar/ProgressBar.java#L163
How did you build this jar? If you use Maven please directly use the pre-built library at https://search.maven.org/artifact/me.tongfei/progressbar/0.9.1/jar.
